services:
  postgres:
    image: postgres:16-alpine
    container_name: employee-task-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: employee_task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d employee_task_db"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - employee-task-network


  backend:
    image: backend-employee-task:latest
    container_name: employee-task-backend
    restart: unless-stopped

    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres123@postgres:5432/employee_task_db
      ENVIRONMENT: docker

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8000:8000"

    networks:
      - employee-task-network


  frontend:
    image: frontend-employee-task:latest
    container_name: employee-task-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3000:80"

    networks:
      - employee-task-network


volumes:
  postgres_data:


networks:
  employee-task-network:
    driver: bridge
